# Build module for all platforms without publishing
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: viamrobotics/build-action@v1.4
        with:
          version: ""  # empty version triggers build-only, no publish
          ref: ${{ github.sha }}
          key-id: ${{ secrets.viam_dev_api_key_id }}
          key-value: ${{ secrets.viam_dev_api_key }}
          token: ${{ github.token }}
