# see https://github.com/viamrobotics/build-action for help
on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and Upload module (linux, darwin)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Publish
        uses: viamrobotics/build-action@v1.4
        with:
          version: ${{ github.event.release.tag_name }}
          ref: ${{ github.sha }}
          key-id: ${{ secrets.viam_dev_api_key_id }}
          key-value: ${{ secrets.viam_dev_api_key }}
          token: ${{ github.token }}

  publish-windows:
    name: Build and Upload module (windows)
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'

      - name: Add MinGW to PATH
        run: echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
        shell: bash

      - name: Set up
        run: make setup
        shell: bash

      - name: Build module
        run: make module.tar.gz
        shell: bash
      
      - name: Upload viamrtsp module to registry
        uses: viamrobotics/upload-module@v1
        with:
          meta-path: meta.json
          module-path: module.tar.gz
          platform: windows/amd64
          version: ${{ github.event.release.tag_name }}
          key-id: ${{ secrets.viam_dev_api_key_id }}
          key-value: ${{ secrets.viam_dev_api_key }}

