# see https://github.com/viamrobotics/build-action for help
on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and Upload module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Publish
        uses: viamrobotics/build-action@v1.4
        with:
          version: ${{ github.event.release.tag_name }}
          ref: ${{ github.sha }}
          key-id: ${{ secrets.viam_dev_api_key_id }}
          key-value: ${{ secrets.viam_dev_api_key }}
          token: ${{ github.token }}
